databases:
  - name: goldcinema_db
    databaseName: goldcinema
    user: goldcinema_user

services:
  - type: web
    name: goldcinema_backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn goldcinema_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: goldcinema_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
